-- MEMBER 테이블에 샘플 데이터 추가 (우선, 회원 프로필 사진은 제외) (5개) --
INSERT INTO MEMBERS (MEMBER_IDX, NAME, ID, PWD, NICKNAME)
VALUES (MEMBER_SEQ.NEXTVAL, '홍일동', 'HONG1', 'dong1', '일동이');
INSERT INTO MEMBERS (MEMBER_IDX, NAME, ID, PWD, NICKNAME)
VALUES (MEMBER_SEQ.NEXTVAL, '홍이동', 'HONG2', 'dong2', '이동이');
INSERT INTO MEMBERS (MEMBER_IDX, NAME, ID, PWD, NICKNAME)
VALUES (MEMBER_SEQ.NEXTVAL, '홍삼동', 'HONG3', 'dong3', '삼동이');
INSERT INTO MEMBERS (MEMBER_IDX, NAME, ID, PWD, NICKNAME)
VALUES (MEMBER_SEQ.NEXTVAL, '홍사동', 'HONG4', 'dong4', '사동이');
INSERT INTO MEMBERS (MEMBER_IDX, NAME, ID, PWD, NICKNAME)
VALUES (MEMBER_SEQ.NEXTVAL, '홍오동', 'HONG5', 'dong5', '오동이');
COMMIT;
-- POSTS 테이블에 샘플 데이터 추가 (10개) --
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '게시글 테스트 1', '게시글 내용 작성 테스트 중 (1)', 
        'MOVIE', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '게시글 테스트 2', '임시 내용 (2)', 
        'BOOK', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 11)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '제목 3', '임시 내용 (3)', 
        'SPORT', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 12)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '제목입니다', '임시 내용 (4)', 
        'MUSIC', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 13)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '제목일까요?', '임시 내용 (5)', 
        'FOOD', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 14)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '게시글 테스트', '게시글 내용 작성 테스트 중 (6)', 
        'MOVIE', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '게시글 테스트 2', '임시 내용 (7)', 
        'BOOK', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 11)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '제목 3', '임시 내용 (8)', 
        'SPORT', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 12)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '제목입니다', '임시 내용 (9)', 
        'MUSIC', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 13)      
);
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '제목일까요?', '임시 내용 (10)', 
        'FOOD', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 14)      
);
COMMIT;
-- COMMENTS 테이블에 샘플 데이터 추가 (10개) --
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 100), '댓글1'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 110), '댓글2'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 120), '댓글3'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 130), '댓글4'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 14),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 140), '댓글5'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 11),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 190), '댓글'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 13),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 180), '댓글'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 14),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 170), '댓글'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 12),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 160), '댓글'
);
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 13),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 150), '댓글'
);

-- POSTS 트리거 실행 --
INSERT INTO POSTS (
            POST_IDX, TITLE, POST_CONTENT, 
            POST_TYPE, MEMBER_IDX)
VALUES (
        POST_SEQ.NEXTVAL, '트리거 테스트', '트리거 테스트 중', 
        'MOVIE', (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 14)      
);

-- COMMENTS 트리거 실행 --
INSERT INTO COMMENTS (COMMENT_IDX, 
                      MEMBER_IDX,
                      POST_IDX, COMM_CONTENT)
VALUES 
        (COMMENT_SEQ.NEXTVAL, 
        (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 12),  
        (SELECT POST_IDX FROM POSTS WHERE POST_IDX = 190), '트리거 테스트'
);

-- 아래 내용은 직접 실행해보시면 좋을것 같아요! (주석 삭제하고 실행해보세요) --
-- 실행하기 전과 후의 FRIENDS 테이블을 비교해보세여@@@@@@@@@@@@@@@
-- 10번 회원이 11번 회원을 친구로 추가하면? --
/*
INSERT INTO FRIENDS (MEMBER_IDX, FRIEND_IDX)
VALUES (
       (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10),
       (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 11)
);
*/
-- 10번 회원이 12번 회원을 친구로 추가하면 --
/*
INSERT INTO FRIENDS (MEMBER_IDX, FRIEND_IDX)
VALUES (
       (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10),
       (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 12)
);
*/
-- 10번 회원이 친구 목록을 조회 하려면? --
/*
SELECT FRIEND_IDX
FROM FRIENDS
WHERE MEMBER_IDX = (SELECT MEMBER_IDX FROM MEMBERS WHERE MEMBER_IDX = 10);
*/
-- 10번 회원이 피드에서 친구들의 게시글을 보려면 --
/*
SELECT P.MEMBER_IDX, P.TITLE, P.POST_CONTENT, P.POST_TYPE
FROM POSTS P
INNER JOIN FRIENDS F ON P.MEMBER_IDX = F.FRIEND_IDX
WHERE F.MEMBER_IDX = 10;
*/
-- 사용자가 100번 게시글에 좋아요를 누르면? --
-- 실행하기 전과 후의 LIKES 테이블을 비교해보세여@@@@@@@@@@@@@@@@@@@@@@
/*
UPDATE LIKES
SET LIKE_NUM = +1
WHERE POST_IDX = 100
;
*/